### ISSUE TITLE
It just broke

### ISSUE THREAD

**Issue by Epicminer26390** [cwmonkey/reactor-knockoff#21] opened 2019-09-20 13:38 UTC
I came back to this after a year and i cannot place anything nothing at all. I don't know what broke but i would like it fixed.

**Comment by asl97** [comment] 2019-09-20 17:15
Let me just says it still works for me.

Without giving some kind of error message, logs, or really anything useful,  unless cwmonkey can somehow reproduce your issue, it would be impossible to fix whatever that broke for you.

"It just broke" isn't very helpful.

**Comment by Epicminer26390** [comment] 2019-09-23 12:30
![Screenshot 2019-09-23 at 8 29 31 AM](https://user-images.githubusercontent.com/36892481/65425626-65161380-dddc-11e9-91eb-bd59f5201b61.png)

This is what happens I click on the cell it does not turn green and stays grey, then it does not allow me to place it.

**Comment by asl97** [comment] 2019-09-23 13:12
Again, not really useful, all that tells me is that some kind of error might have happened and it most likely stopped the javascript event loop but not the error itself or the cause.

If you really don't know where to look,  look up `"browser console"` on a search engine,  on most browser, f12 should bring it up.

**Comment by Epicminer26390** [comment] 2019-09-23 15:45
so I don't know what happened but i was screwing around with the website it started to work again so :P

**Comment by Epicminer26390** [comment] 2019-09-24 13:33
Never mind it broke unfortunately, so what do you want me to do just open view page source?

**Comment by asl97** [comment] 2019-09-24 19:19
![image](https://user-images.githubusercontent.com/4752645/65543112-120aa080-df43-11e9-82e4-5249f2182aad.png)
^Console

If there is an error, it would be in red.

**Comment by 1993mrc** [comment] 2019-11-03 15:40
![123456](https://user-images.githubusercontent.com/57323220/68087720-8e54a580-fe58-11e9-8efa-021c9e8a9013.png)

I have the same issue

**Comment by 1993mrc** [comment] 2019-11-03 16:05
![1234567](https://user-images.githubusercontent.com/57323220/68088112-14262000-fe5c-11e9-8c32-b5f5bfeb091f.png)

It appears also on newest version

**Comment by asl97** [comment] 2019-11-04 03:04
This is due to undocumented changes that chrome did,  they added something call `part` to the dom interface.

@1993mrc I doubt I caught every usage of `part` but it seem to work, let me know if it's still broken somewhere.

**Comment by 1993mrc** [comment] 2019-11-04 09:51
so I have a big request to You, can you help me with solving that issue? at this moment is the only place where it appears but it completely breaks the game. On Microsoft Edge it works correctly but there are another problem with resolution - it "jumps" and expand on available place on screen (when browser window is minimized to game scale it only "jumps" to few pixels)

**Comment by asl97** [comment] 2019-11-04 16:23
@1993mrc if you mean this issue, I have already pushed the fix to my fork.
as for the "jumps", I don't quite understand the issue, if it affect cwmonkey version too, I would appreciate it if you create another seperate issue for it.

**Comment by cwmonkey** [comment] 2019-11-10 01:57
Ew. Fixed in 754a441de9c91b226faace94ea092a447429b398 hopefully.

**Closed by cwmonkey** 2019-11-10 01:57 UTC

**Comment by asl97** [comment] 2019-11-10 03:13
:rofl: you even changed the description, kind of overkill but should totally catch everything.

**Comment by cwmonkey** [comment] 2019-11-10 03:17
Oh dammit I thought I fixed all those :P
