### ISSUE TITLE
Animated parts

### ISSUE THREAD

**Issue by Wad67** [cwmonkey/reactor-knockoff#3] opened 2016-01-21 06:22 UTC
You can animate the gifs for reactor components.
Some simple editing in paint.net allows for fans to spin and so forth.
I was thinking of reactor cells emitting an unhealthy looking green glow.

Only problem I have found so far is that the alpha channels get ruined, not sure if it's the plugin I am using tho.
![vent_1](https://cloud.githubusercontent.com/assets/991507/12473135/29370218-c05b-11e5-969d-77cae2e29922.gif)

**Comment by Wad67** [comment] 2016-01-21 06:24
![cell_1_1](https://cloud.githubusercontent.com/assets/991507/12473167/6fad02ba-c05b-11e5-8db6-4c96377caf09.gif)

**Comment by Wad67** [comment] 2016-01-21 06:27
![lab](https://cloud.githubusercontent.com/assets/991507/12473208/e16a65aa-c05b-11e5-8365-a765e3f2e1f8.gif)

**Comment by Wad67** [comment] 2016-01-21 06:28
![lab](https://cloud.githubusercontent.com/assets/991507/12473222/01a3712c-c05c-11e5-9d8b-38c712fba386.gif)

**Comment by Wad67** [comment] 2016-01-21 06:28
Not much of an artist, but you get the idea

**Comment by Wad67** [comment] 2016-01-21 06:33
I tried replacing the accelerator graphic with a picture of a jam drop, needless to say it didn't work.
Would be cool if we could have hi res graphics tho. (Jamdrops ftw)
![didunt work](https://cloud.githubusercontent.com/assets/991507/12473294/befc539c-c05c-11e5-9e5d-87f82312bb51.png)

**Comment by Wad67** [comment] 2016-01-21 06:36
Graphics ingame are animated, just have a white background (I think it's the fact that i am using layers as frames(like an onion(or a cake(or an ogre))))
![g_issue](https://cloud.githubusercontent.com/assets/991507/12473329/10b25d30-c05d-11e5-812a-5cdbbaafb6c2.png)

**Comment by Wad67** [comment] 2016-01-21 06:40
Also the chronometer looks like a flux capacitor.

**Comment by cwmonkey** [comment] 2016-01-21 07:09
Thanks for the feedback, I'll look into perhaps adding some subtle animations. 

And yeah, animated gifs can't have alpha channels (only 100% transparency). 

> Also the chronometer looks like a flux capacitor.

It sure does :D 

I'm going to close this since it's not a bug/issue, but feel free to give more feedback if you'd like.

**Closed by cwmonkey** 2016-01-21 07:09 UTC

**Comment by Wad67** [comment] 2016-01-21 12:19
I might start making a texture pack

**Comment by Wad67** [comment] 2016-01-21 13:04
One other thing, you can easily bump up the tile resolution to 64x64 just by editing app.css
